import logging
from abc import abstractmethod, ABC
from copy import deepcopy
from dataclasses import dataclass, field

import numpy as np

from pycram import logger

from typing_extensions import List, Optional, Iterator

from giskardpy.executor import Executor
from giskardpy.motion_statechart.context import MotionStatechartContext
from giskardpy.motion_statechart.goals.collision_avoidance import (
    ExternalCollisionAvoidance,
)
from giskardpy.motion_statechart.goals.templates import Sequence
from giskardpy.motion_statechart.graph_node import EndMotion
from giskardpy.motion_statechart.motion_statechart import MotionStatechart
from giskardpy.motion_statechart.tasks.cartesian_tasks import CartesianPose
from giskardpy.qp.exceptions import InfeasibleException
from giskardpy.qp.qp_controller_config import QPControllerConfig
from krrood.adapters.json_serializer import list_like_classes
from pycram.config.action_conf import ActionConfig
from pycram.datastructures.dataclasses import Context
from pycram.datastructures.enums import (
    Arms,
    ApproachDirection,
    VerticalAlignment,
)
from pycram.datastructures.grasp import GraspDescription, GraspPose
from pycram.plans.failures import RobotInCollision
from pycram.locations.costmaps import (
    OccupancyCostmap,
    VisibilityCostmap,
    GaussianCostmap,
    Costmap,
    OrientationGenerator,
    RingCostmap,
)
from pycram.pose_validator import (
    visibility_validator,
    collision_check,
    pose_sequence_reachability_validator,
)
from pycram.utils import link_pose_for_joint_config
from pycram.view_manager import ViewManager
try:
    from semantic_digital_twin.adapters.ros.visualization.pose_publisher import (
        PosePublisher,
    )
    from semantic_digital_twin.adapters.ros.visualization.viz_marker import (
        VizMarkerPublisher,
    )
except ModuleNotFoundError as e:
    logger.warning(f"Could not import modules from ros adapter: {e}")
    PosePublisher = None
    VizMarkerPublisher = None

from semantic_digital_twin.collision_checking.collision_rules import (
    AvoidExternalCollisions,
)
from semantic_digital_twin.robots.abstract_robot import AbstractRobot
from semantic_digital_twin.spatial_types.spatial_types import Pose
from semantic_digital_twin.world import World
from semantic_digital_twin.world_description.connections import FixedConnection
from semantic_digital_twin.world_description.world_entity import Body

logger = logging.getLogger("pycram")


@dataclass
class Location(ABC):
    """
    A location is a pose in the world that can be used to plan movements.
    """

    context: Optional[Context] = field(default=None, kw_only=True)
    """
    The context where the location can extract information about the robot and world from.
    """

    @property
    def world(self):
        return self.context.world

    @property
    def robot(self):
        return self.context.robot

    def ground(self) -> Pose:
        """
        :return: The first pose generated by this location designator
        """
        return next(iter(self))

    @abstractmethod
    def __iter__(self) -> Iterator[Pose]:
        """
        :return: An iterator over all poses generated by this location designator
        """


@dataclass
class CostmapLocation(Location):
    """
    Uses Costmaps to create locations for complex constraints
    """

    target: Pose
    """
    The target pose for which the location should be calculated.
    """

    reachable: bool = False
    """
    Rather the costmap should be used for reaching or not.
    """

    visible: bool = False
    """
    Rather the costmap should be used for visibility or not.
    """

    reachable_arm: Optional[Arms] = None
    """
    The arm that should be used to reach the target.
    """

    grasp_description: Optional[GraspDescription] = None
    """
    A grasp description that should be used to calculate the pose.
    """

    def resolve(self) -> Pose:
        return next(iter(self))

    def setup_costmaps(self, target: Pose, visible: bool, reachable: bool) -> Costmap:
        """
        Sets up the costmap for the given target and robot.
        The costmap are merged and stored in the final_map
        """
        ground_pose = deepcopy(target)
        ground_pose.z = 0

        base_bb = self.robot.base.bounding_box

        occupancy = OccupancyCostmap(
            distance_to_obstacle=(base_bb.depth / 2 + base_bb.width / 2) / 2,
            world=self.world,
            robot_view=self.robot,
            width=200,
            height=200,
            resolution=0.02,
            origin=ground_pose,
        )
        final_map = occupancy

        if visible:
            camera = list(self.robot.neck.sensors)[0]
            visible = VisibilityCostmap(
                min_height=camera.minimal_height,
                max_height=camera.maximal_height,
                world=self.world,
                width=200,
                height=200,
                resolution=0.02,
                origin=target,
            )
            final_map += visible

        if reachable:
            ring = RingCostmap(
                resolution=0.02,
                width=200,
                height=200,
                std=15,
                distance=0.4,  # That needs to be replaced with an estimate of the reachability space of the robot arms
                world=self.world,
                origin=target,
            )
            final_map += ring

        return final_map

    def get_object_in_hand(
        self, test_robot: AbstractRobot, test_world: World
    ) -> List[Body]:

        manipulator = ViewManager.get_end_effector_view(
            self.reachable_arm if self.reachable_arm is not None else Arms.BOTH,
            test_robot,
        )
        manipulators = (
            [manipulator]
            if not isinstance(manipulator, list_like_classes)
            else manipulator
        )
        objs = set()
        for man in manipulators:
            objs.update(
                test_world.get_kinematic_structure_entities_of_branch(man.tool_frame)
            )
            objs.remove(man.tool_frame)
        return list(objs)

    def __iter__(self) -> Iterator[Pose]:
        """
        Generates positions for a given set of constrains from a costmap and returns
        them. The generation is based of a costmap which itself is the product of
        merging costmaps, each for a different purpose. In any case an occupancy costmap
        is used as the base, then according to the given constrains a visibility or
        gaussian costmap is also merged with this. Once the costmaps are merged,
        a generator generates pose candidates from the costmap. Each pose candidate
        is then validated against the constraints given by the designator if all validators
        pass the pose is considered valid and yielded.

           :yield: An instance of CostmapLocation.Location with a valid position that satisfies the given constraints
        """

        test_world = deepcopy(self.world)

        test_world.name = "Test World"

        if self.context.debug:
            VizMarkerPublisher(
                _world=test_world, node=self.context.ros_node
            ).with_tf_publisher()

        robot = self.robot

        test_robot = robot.from_world(test_world)

        objects_in_hand = self.get_object_in_hand(test_robot, test_world)
        object_in_hand = objects_in_hand[0] if objects_in_hand else None

        final_map = self.setup_costmaps(self.target, self.visible, self.reachable)
        final_map.number_of_samples = 600
        final_map.orientation_generator = (
            OrientationGenerator.orientation_generator_for_axis(
                list(self.robot.base.main_axis.to_np())
            )
        )

        for pose_candidate in final_map:
            logger.debug(f"Testing candidate pose at {pose_candidate}")
            odom_height = test_world.compute_forward_kinematics(
                test_world.root,
                test_robot.root.parent_kinematic_structure_entity,
            ).z
            pose_candidate.z = odom_height
            test_robot.root.parent_connection.origin = pose_candidate

            collisions = collision_check(
                robot=test_robot,
                world=test_world,
            )

            if collisions:
                logger.debug(f"Candidate pose in collision, skipping")
                continue

            if not (self.reachable or self.visible):
                self._last_result = pose_candidate
                yield pose_candidate
                continue

            if self.visible and not visibility_validator(
                test_robot, self.target, test_world
            ):
                logger.debug(f"Candidate pose not visible, skipping")
                continue

            if not self.reachable:
                self._last_result = pose_candidate
                yield pose_candidate
                continue

            grasp_descriptions = (
                [self.grasp_description]
                if self.grasp_description
                else GraspDescription.calculate_grasp_descriptions(
                    ViewManager.get_arm_view(
                        self.reachable_arm, test_robot
                    ).manipulator,
                    self.target,
                )
            )

            for grasp_description in grasp_descriptions:
                target_sequence = grasp_description._pose_sequence(
                    self.target, object_in_hand
                )

                if self.context.debug:
                    PosePublisher(
                        pose=target_sequence[1],
                        node=self.context.ros_node,
                        _world=self.world,
                        lifetime=10,
                    )

                ee = ViewManager.get_arm_view(self.reachable_arm, test_robot)
                is_reachable = pose_sequence_reachability_validator(
                    target_sequence,
                    ee.manipulator.tool_frame,
                    test_robot,
                    test_world,
                    use_fullbody_ik=test_robot.full_body_controlled,
                )
                if is_reachable:
                    pose = GraspPose.from_pose(
                        pose=pose_candidate,
                        arm=self.reachable_arm,
                        grasp_description=grasp_description,
                    )
                    self._last_result = pose
                    yield pose


@dataclass
class AccessingLocation(Location):
    """
    Location designator which describes poses used for opening drawers
    """

    handle: Body
    """
    The handle of the drawer.
    """

    arm: Arms
    """
    The arm that should be used to touch the handle
    """

    prepose_distance: Optional[float] = None
    """
    The prepose distance used to approach the drawer handle.
    Defaults to ActionConfig.grasping_prepose_distance
    """

    def __post_init__(self):
        self.prepose_distance = (
            ActionConfig.grasping_prepose_distance
            if self.prepose_distance is None
            else self.prepose_distance
        )

    @staticmethod
    def adjust_map_for_drawer_opening(
        cost_map: Costmap,
        init_pose: Pose,
        goal_pose: Pose,
        width: float = 0.2,
    ):
        """
        Adjust the cost map for opening a drawer. This is done by removing all locations between the initial and final
        pose of the drawer/container.

        :param cost_map: Costmap that should be adjusted.
        :param init_pose: Pose of the drawer/container when it is fully closed.
        :param goal_pose: Pose of the drawer/container when it is fully opened.
        :param width: Width of the drawer/container.
        """
        motion_vector = [
            goal_pose.x - init_pose.x,
            goal_pose.y - init_pose.y,
            goal_pose.z - init_pose.z,
        ]
        # remove locations between the initial and final pose
        motion_vector_length = np.linalg.norm(motion_vector)
        unit_motion_vector = np.array(motion_vector) / motion_vector_length
        orthogonal_vector = np.array([unit_motion_vector[1], -unit_motion_vector[0], 0])
        orthogonal_vector /= np.linalg.norm(orthogonal_vector)
        orthogonal_size = width
        map_origin_idx = cost_map.map.shape[0] // 2, cost_map.map.shape[1] // 2
        for i in range(int(motion_vector_length / cost_map.resolution)):
            for j in range(int(orthogonal_size / cost_map.resolution)):
                idx = (
                    int(
                        map_origin_idx[0]
                        + i * unit_motion_vector[0]
                        + j * orthogonal_vector[0]
                    ),
                    int(
                        map_origin_idx[1]
                        + i * unit_motion_vector[1]
                        + j * orthogonal_vector[1]
                    ),
                )
                cost_map.map[idx] = 0
                idx = (
                    int(
                        map_origin_idx[0]
                        + i * unit_motion_vector[0]
                        - j * orthogonal_vector[0]
                    ),
                    int(
                        map_origin_idx[1]
                        + i * unit_motion_vector[1]
                        - j * orthogonal_vector[1]
                    ),
                )
                cost_map.map[idx] = 0

    def setup_costmaps(self, handle: Body) -> Costmap:
        """
        Sets up the costmaps for the given handle and robot. The costmaps are merged and stored in the final_map.
        """
        ground_pose = handle.global_pose
        ground_pose.z = 0

        base_bb = self.robot.base.bounding_box
        occupancy = OccupancyCostmap(
            robot_view=self.robot,
            distance_to_obstacle=(base_bb.depth / 2 + base_bb.width / 2) / 2,
            width=200,
            height=200,
            resolution=0.02,
            origin=ground_pose,
            world=handle._world,
        )
        final_map = occupancy

        gaussian = GaussianCostmap(
            mean=200, sigma=15, world=handle._world, resolution=0.02, origin=ground_pose
        )
        final_map += gaussian

        return final_map

    def create_target_sequence(self) -> List[Pose]:
        """
        Creates the sequence of target poses
        :return:
        """
        # compute the chain of connections only works top down,
        handle_to_root_connections = list(
            reversed(
                self.handle._world.compute_chain_of_connections(
                    self.handle._world.root, self.handle
                )
            )
        )
        # Search for the first connection that is not a FixedConnection,
        container_connection = list(
            filter(
                lambda c: not isinstance(c, FixedConnection), handle_to_root_connections
            )
        )[0]

        lower_limit = container_connection.dof.limits.lower.position
        upper_limit = container_connection.dof.limits.upper.position

        init_pose = link_pose_for_joint_config(
            self.handle, {container_connection.dof.name.name: lower_limit}
        )

        # Calculate the pose the handle would be in if the drawer was to be fully opened
        goal_pose = link_pose_for_joint_config(
            self.handle, {container_connection.dof.name.name: upper_limit}
        )

        # Handle position for calculating rotation of the final pose
        half_pose = link_pose_for_joint_config(
            self.handle, {container_connection.dof.name.name: upper_limit / 1.5}
        )

        target_sequence = [init_pose, half_pose, goal_pose]
        return target_sequence

    def __iter__(self) -> Iterator[Pose]:
        """
        Creates poses from which the robot can open the drawer specified by the ObjectPart designator describing the
        handle. Poses are validated by checking if the robot can grasp the handle while the drawer is closed and if
        the handle can be grasped if the drawer is open.

        :yield: A location designator containing the pose and the arms that can be used.
        """
        test_world = deepcopy(self.world)
        test_robot = self.robot.from_world(test_world)

        final_map = self.setup_costmaps(self.handle)

        target_sequence = self.create_target_sequence()
        half_pose = target_sequence[1]

        orientation_generator = (
            lambda p, o: OrientationGenerator.generate_origin_orientation(p, half_pose)
        )
        final_map.number_of_samples = 600
        final_map.orientation_generator = orientation_generator
        for pose_candidate in final_map:
            pose_candidate.z = 0
            test_robot.root.parent_connection.origin = pose_candidate
            try:
                collision_check(test_robot, test_world)
            except RobotInCollision:
                continue

            for arm_chain in test_robot.manipulator_chains:
                grasp = GraspDescription(
                    ApproachDirection.FRONT,
                    VerticalAlignment.NoAlignment,
                    arm_chain.manipulator,
                ).grasp_orientation()
                grasp.reference_frame = test_world.root
                current_target_sequence = [deepcopy(pose) for pose in target_sequence]
                grasp_rotation = grasp.to_rotation_matrix()
                current_target_sequence = [
                    grasp_rotation @ pose for pose in current_target_sequence
                ]

                is_reachable = pose_sequence_reachability_validator(
                    current_target_sequence,
                    arm_chain.manipulator.tool_frame,
                    test_robot,
                    test_world,
                    use_fullbody_ik=test_robot.full_body_controlled,
                )
                if is_reachable:
                    yield pose_candidate


@dataclass
class GiskardLocation(Location):
    """
    Finds a standing pose for a robot such that the TCP of the given arm can reach the target_pose. This Location
    Designator uses Giskard and full body control to find a pose for the robot base.
    """

    target_pose: Pose
    """
    Target pose for which a standing pose should be found. 
    """

    arm: Arms
    """
    Arm which should read the target pose
    """

    grasp_description: Optional[GraspDescription] = None
    """
    The grasp description which should be used to grasp the target pose, used if there is a body at the pose
    """

    threshold: float = field(default=0.02)
    """
    Threshold between the TCP of the arm and the target pose at which a stand pose if deemed successfull
    """

    def setup_costmap(self, pose: Pose) -> Costmap:
        """
        Setup the reachability costmap for initial pose estimation.
        """
        ground_pose = deepcopy(pose)
        ground_pose.z = 0.0

        base_bb = self.robot.base.bounding_box

        occupancy_map = OccupancyCostmap(
            resolution=0.02,
            height=200,
            width=200,
            world=self.world,
            robot_view=self.robot,
            origin=ground_pose,
            distance_to_obstacle=(base_bb.width / 2 + base_bb.depth / 2) / 2,
        )
        gaussian_map = GaussianCostmap(
            resolution=0.02,
            origin=ground_pose,
            mean=200,
            sigma=15,
            world=self.world,
        )

        reachability_map = occupancy_map + gaussian_map
        reachability_map.number_of_samples = 10

        return reachability_map

    def setup_giskard_executor(
        self,
        pose_sequence: List[Pose],
        world: World,
        robot_view: AbstractRobot,
        end_effector: Body,
    ) -> Executor:
        """
        Setup the Giskard executor for a specific pose sequence and a given world.

        :param pose_sequence: The pose sequence which the end_effector should follow
        :param world: The world in which the pose sequence should be executed
        :param robot_view: The robot view of the robot which should be used for the execution, needs to fit the world
        :param end_effector: The end effector which should be controlled by Giskard
        :return: The Giskard executor for the pose sequence
        """
        pose_seq = Sequence(
            nodes=[
                CartesianPose(
                    root_link=world.root,
                    tip_link=end_effector,
                    goal_pose=pose,
                )
                for pose in pose_sequence
            ]
        )
        with world.modify_world():
            world.collision_manager.clear_temporary_rules()
            world.collision_manager.add_temporary_rule(
                AvoidExternalCollisions(
                    robot=robot_view, buffer_zone_distance=0.1, violated_distance=0.0
                )
            )
        msc = MotionStatechart()
        msc.add_nodes(
            [
                pose_seq,
                ExternalCollisionAvoidance(
                    robot=robot_view, cancel_if_collision_violated=False
                ),
            ]
        )
        msc.add_node(EndMotion.when_true(pose_seq))

        executor = Executor(
            MotionStatechartContext(
                world=world,
                qp_controller_config=QPControllerConfig(
                    target_frequency=50, prediction_horizon=4, verbose=False
                ),
            ),
        )
        executor.compile(msc)

        return executor

    def __iter__(self) -> Iterator[GraspPose]:

        reachability_map = self.setup_costmap(self.target_pose)

        ee = ViewManager.get_arm_view(self.arm, self.robot)

        test_world = deepcopy(self.world)
        test_world.name = "Test World"

        test_robot = self.robot.__class__.from_world(test_world)
        test_ee = test_world._get_world_entity_by_hash(hash(ee.manipulator.tool_frame))
        with test_world.modify_world():
            test_robot._setup_collision_rules()

        for candidate in reachability_map:

            grasp_descriptions = (
                [self.grasp_description]
                if self.grasp_description
                else GraspDescription.calculate_grasp_descriptions(
                    (
                        test_robot.left_arm.manipulator
                        if self.arm == Arms.LEFT
                        else test_robot.right_arm.manipulator
                    ),
                    self.target_pose,
                )
            )

            for grasp_desc in grasp_descriptions:

                target_sequence = grasp_desc._pose_sequence(self.target_pose)

                test_robot.root.parent_connection.origin = candidate

                executor = self.setup_giskard_executor(
                    target_sequence, test_world, test_robot, test_ee
                )

                try:
                    executor.tick_until_end()
                except (TimeoutError, InfeasibleException) as e:
                    pass

                dist = test_ee.global_pose.to_position().euclidean_distance(
                    target_sequence[-1].to_position()
                )

                if dist > 0.02:
                    continue

                ret = GraspPose.from_pose(
                    test_robot.root.global_pose,
                    grasp_description=grasp_desc,
                    arm=self.arm,
                )
                yield ret
