# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: KRROOD
author: AICOR Institute for Artificial Intelligence
logo: _static/images/krrood_logo.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  extra_extensions:
    - myst_nb
    - sphinxcontrib.bibtex  # Add the BibTeX extension
    - autoapi.extension  # Add the AutoAPI extension
    - 'sphinx.ext.autodoc'
    - sphinxcontrib.plantuml
    - sphinxcontrib.mermaid
  config:
    bibtex_bibfiles:
      - references.bib
    # AutoAPI configuration
    autoapi_type: python
    autoapi_dirs:
      - ../src
    autoapi_options:
      - members
      - undoc-members
      - show-inheritance
      - show-module-summary
    autoapi_add_toctree_entry: True


# Information about where the book exists on the web
repository:
  url: https://github.com/code-iai/krrood  # Online location of your book
  path_to_book: doc  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
