name: Run tests and build the Python distribution

on:
  push:
    branches:
      - master

  # --------------------------------------------------------------------------------------------------------------------

  workflow_call:
    inputs:
      version:
        required: true
        type: string

      python-versions:
        required: true
        type: string
        default: "cp38-cp38"

# ----------------------------------------------------------------------------------------------------------------------

defaults:
  run:
    shell: bash
    working-directory: random_events

# ----------------------------------------------------------------------------------------------------------------------

concurrency:
  group: 'random-events-building-and-deployment'
  cancel-in-progress: true

# ----------------------------------------------------------------------------------------------------------------------

jobs:
  test-and-build:
    name: Build and Test the Python distribution
    runs-on: ubuntu-latest

    steps:

      - name: Checkout 🛎
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      # ----------------------------------------------------------------------------------------------------------------

      - name: Setup python 🐍
        uses: actions/setup-python@v4
        with:
            python-version: "3.12"
            cache: pip

      # ----------------------------------------------------------------------------------------------------------------

      - name: Install Bazel 7.0.0
        run: |
          BAZEL_VERSION=7.0.0
          curl -L -o bazel.sh \
            https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh
          chmod +x bazel.sh
          ./bazel.sh --user
          echo "$HOME/bin" >> $GITHUB_PATH

      # ----------------------------------------------------------------------------------------------------------------

      - name: Install dependencies
        run: |
          pip install pytest
          pip install -r requirements-dev.txt

      # ----------------------------------------------------------------------------------------------------------------

      - name: Build and test C++ lib
        working-directory: random_events/src/random_events_lib
        run: |
          bazel build //test:test_all
          bazel test //test:test_all


      # ----------------------------------------------------------------------------------------------------------------

      - name: Run Tests 🎓
        run: |
          pytest ../test/random_events_test